services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - gpio-service
      - metrics-service

  postgis:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gpio-service:
    build: ./services/gpio
    environment:
      - DB_HOST=postgis
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "8080:8080"
    volumes:
      - ./services/gpio:/app/src
    depends_on:
      - postgis

  metrics-service:
    build: ./services/metrics
    environment:
      - DB_HOST=postgis
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "8081:8081"
    volumes:
      - ./services/metrics:/app/src
    depends_on:
      - postgis

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  default:
    name: app_network

